---

- name: Install PECL uploadprogress
  shell: pecl install uploadprogress
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
